default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: partiu_production
  username: partiu
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
