# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72cbccc1edda4cdcd13617d2c50124ea1429a1e714296a3f069aeacc3cf0770f6964700349feec550f3e230fd0c90e94afd1f658bb58fe23e92b578158514d53

test:
  secret_key_base: 772eb251fc74f7d1705ca75ceaef99d3385a76359b030916a44e55b2eb9c58cb7aa158c98b939082a895c26ea9c3c4c06d9a29f782bbc3aaf8ec3993d985f407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
